### ISSUE TITLE
Group tags by letter doesn't work

### ISSUE THREAD

**Issue by niemiec** [saimn/simple-theme-piwigo#16]
Hi,

On my site group tags by letter doesn't work. The site is empty: http://d29-139.pl/tags.php?display_mode=letters Tag's cloud looks ok.

**Comment by saimn** [comment]
A fix was applied to simple grey: http://piwigo.org/dev/changeset/25487
Maybe the same could work for simpleng, if you want to test (Sorry I miss time to maintain this theme and I don't use piwigo anymore ...).

**Comment by niemiec** [comment]
Yep, it's work, thanks :)

Too bad that they do not develop this theme. For me it is the most beautiful.

**Comment by saimn** [comment]
The fix is available in version 3.2.3
