### ISSUE TITLE
Warning / Theme Broken

### ISSUE THREAD

**Issue by jmalais** [saimn/simple-theme-piwigo#17]
I'm getting an error:

Warning: filemtime(): stat failed for ./themes/simpleng/js/jquery-1.9.1.min.js in /home5/jmalaisc/public_html/_photos/include/template.class.php on line 1894

at www.photos.jmalais.com

This was a fresh Piwigo install and I just added your theme. I looked for installation documentation but found none so I assume this is something wrong with the script?

**Comment by saimn** [comment]
It seems to be an error with the installation, check in the folder if the files are present, or try to reinstall.

**Comment by andi-blafasl** [comment]
I have just installed your theme in a fresh piwigo 2.7.4 installation and getting the same error. Seems to be problem with case sensitive operating systems. Piwigo installed the theme in the folder "SimpleNG" and the links in your files are all lower case.
I tried to rename the folder but that broke piwigo completely. The theme was disabled after the renaming and could not be activated again.
Maybe you have to change the Theme name in the Piwigo installer? Or change your links to be upper case like the name?

**Comment by saimn** [comment]
Ok I found the issue: for the previous release I used the new git uploader in the piwigo extensions site, and it was naming the root directory SimpleNG instead of simpleng ... So I released a new version with a manual upload. Thanks for your help on this.
